export const COPY_EN = {
  locale: "en",
  productName: "AI Workbench Studio",
  shortName: "AIWS",
  tagline: "Local-first AI workbench for projects, files, and traceable outputs.",
  brandCompact: "Workbench",
  nav: {
    home: "Chat",
    newChat: "New Chat",
    newProject: "New Project",
    actions: "Workflow Apps",
    settings: "Settings",
    projects: "Projects",
    chats: "Chats",
    workspace: "Workspace",
    oneOffChats: "One-off chats",
    searchPlaceholder: "Search chat titles",
    noSearchResults: "No results.",
  },
  topbar: {
    localFirst: "Local-first",
    contextOpen: "Close Context & Files",
    contextClosed: "Open Context & Files",
    modeLabel: "Mode",
  },
  home: {
    title: "Local AI Workbench",
    askTitle: "Ask AIWS",
    askSubtitle: "Type a question. Attach files if needed.",
    projectStartHint: "First message creates a saved project chat.",
    subtitle: "Start a work session from a question, file, or project. Runs and artifacts stay inspectable.",
    workSessionEyebrow: "Start work",
    workSessionTitle: "Start a work session",
    workSessionBody: "Ask once, start from a file, or create a project workspace. AIWS records the context, run, and artifact when there is something to keep.",
    laneAsk: "Ask once",
    laneAskBody: "Use chat for a quick answer.",
    laneFile: "Start from file",
    laneFileBody: "Attach PDF, image, CSV, DOCX, or text.",
    laneFileReady: "File attached. Choose a tool below.",
    laneProject: "Create project",
    laneProjectBody: "Keep goals, files, workflow apps, runs, and artifacts together.",
    factActions: "available tools",
    factRuns: "saved runs",
    factArtifacts: "artifacts",
    quickActions: "Chat Tools",
    quickActionsHint: "Use one-off tools in chat, then save repeatable work as a Workflow App in a project.",
    recentRuns: "Recent Work",
    recentArtifacts: "Recent Artifacts",
    artifacts: "Artifacts",
    configure: "Configure",
    useInput: "Use attached file",
    prepareBrief: "Write brief",
    createArtifact: "Run tool",
    createPrompt: "Create brief",
    creating: "Creating",
    notAvailable: "Planned",
    needsFile: "Needs file",
    ready: "Ready",
    readyToRun: "Ready to create a traceable tool run and output.",
    openTable: "Open table",
    workbenchOutputs: "Outputs",
    hintCreateTitle: "Create a Workbench Output",
    hintCreateBody: "Start document, image, CSV, or code work before creating a project.",
    hintInspectTitle: "Inspect Work and Artifacts",
    hintInspectBody: "Each output keeps its input snapshot, status, log, and clickable artifacts.",
    hintPromoteTitle: "Promote repeatable work",
    hintPromoteBody: "Save useful flows into projects, workflow apps, and configurable panels.",
    attachRequired: "Attach a file before creating this artifact.",
    codexBriefRequired: "Describe the situation and desired change before creating a Codex brief.",
    codexBriefHint: "Write the situation first: what changed, which files matter, and what done means.",
    runBeforeProject: "Use a one-off Chat Tool",
    runHistory: "Work history",
    starterEmpty: "Create an artifact or Codex brief to keep the plan, log, and output here.",
    starterEmptyAction: "Run history appears after a Chat Tool creates a persisted run.",
    artifactEmpty: "Markdown, CSV, JSON, and report outputs appear as clickable objects.",
    artifactEmptyAction: "Artifacts appear after a run writes a real file.",
  },
  table: {
    eyebrow: "Table Workbench",
    title: "Analyze CSV, Excel, or pasted tables",
    emptyDrop: "Drop CSV/XLS/XLSX here, choose a file, or paste table cells below",
    pastedHint: "Copied spreadsheet cells become a temporary CSV attachment and fill the preview table.",
    chooseFile: "Choose file",
    analyze: "Analyze table",
    analyzing: "Analyzing...",
    close: "Close",
    pastePlaceholder: "Paste cells from Excel, Numbers, Sheets, or a tab-separated table",
    noPreview: "No preview yet.",
    noPreviewHint: "CSV and pasted tables preview here. XLS/XLSX files are parsed by the backend when you run analysis.",
  },
  catalog: {
    title: "Workflow Apps & Chat Tools",
    eyebrow: "Workbench catalog",
    body: "Chat Tools are one-off helpers inside a conversation. Workflow Apps are repeatable project apps backed by aiws.yaml, runs, and artifacts.",
    tools: "Chat Tools",
    toolsBody: "Use these once inside chat with files, pasted tables, or web approval.",
    apps: "Workflow Apps",
    appsBody: "Install or configure these inside a project when the work repeats.",
    recentRuns: "Recent runs",
    recommendedProjects: "Recommended connections",
    input: "Input",
    output: "Output",
    scope: "Scope",
    viewer: "Viewer",
    oneOffTool: "One-off Chat Tool",
    workflowApp: "Repeatable Workflow App",
    answerViewer: "Chat answer",
    openTool: "Open tool",
    connectProject: "Connect project",
    noRuns: "No recent runs yet. Run a tool or project app to populate this catalog.",
    investmentTitle: "Investment Rebalancing",
    investmentBody: "Portfolio CSVs plus ETF/stock interests become a repeatable research and rebalance workspace.",
    fitnessTitle: "Food / Diet / Exercise Planner",
    fitnessBody: "Planned Workflow App for structured goals, logs, and repeatable health reports.",
    dataResourceTitle: "Data Resource",
    dataResourceBody: "Typed artifacts such as CSV profiles, reports, and JSON outputs can move between projects.",
  },
  inspector: {
    title: "Context & Files",
    powerTitle: "Right Inspector",
    emptyPurpose: "Start a chat to see the files, context, goals, runs, and diagnostics used by this workspace.",
    currentContext: "Current Context",
    tabs: {
      context: "Context",
      files: "Files",
      memory: "Memory",
      runs: "Runs",
      artifacts: "Artifacts",
      diagnostics: "Diagnostics",
    },
    diagnosticsWarning: "Public tunnel is active. Do not expose diagnostics without authentication.",
    factChunks: "chunks",
    factFiles: "files",
    factRuns: "runs",
    factArtifacts: "artifacts",
    includedChunks: "Included retrieval chunks",
    currentTask: "Current Task",
    local: "Local",
    cloud: "Cloud",
    files: "files",
    receipts: "receipts",
    calls: "calls",
    nextActions: "Next actions",
    attachOrPaste: "Attach or paste an input",
    runAction: "Run table/document tool",
    saveUsefulAnswer: "Save useful answer as artifact",
    sendToCreateReceipt: "Send a message to create a receipt",
    promoteTitle: "Promote to project",
    promoteBody: "Move this chat, files, receipts, and future artifacts into a new private project.",
    promote: "Promote",
    promoting: "Promoting...",
    workSession: "WorkSession",
  },
  messageActions: {
    saveArtifact: "Save as artifact",
    saving: "Saving...",
    saved: "Saved",
    download: "Download answer",
  },
  settings: {
    title: "Workspace Settings",
    close: "Close",
    savedMessages: "Saved messages",
    aiRequests: "AI requests",
    monthlyApiCost: "API cost this month",
    profile: "Profile",
    avatar: "Profile photo",
    name: "Name",
    age: "Age",
    role: "Job / role",
    language: "Language",
    personalContext: "Personal Context",
    situation: "Situation / chat context",
    addMemory: "Add to memory",
    memoryPlaceholder: "Write anything the workbench should remember later.",
    interface: "Interface",
    uiMode: "UI mode",
    easyMode: "Easy Mode - focused workspace",
    powerMode: "Power Mode - diagnostics and execution details",
    modeHelp: "Easy keeps model and file controls visible while hiding operator logs. Power shows execution paths, cost, prompts, and runtime details.",
    saveProfile: "Save profile",
    monthlyApiForecast: "This month forecast",
    allAccountForecast: "All accounts forecast",
  },
  modelPicker: {
    title: "Select AI Model",
    easyTitle: "Choose model",
    easyHint: "Pick local, cloud, or the recommended option.",
    showDetails: "Detailed settings",
    hideDetails: "Simple view",
    selected: "selected",
    local: "Local",
    localMac: "Local Mac",
    cloudAi: "Cloud AI",
    freeLocal: "Free · local",
    paidCloud: "Paid · cloud",
    keyReady: "Key ready",
    keyMissing: "Key missing",
    keyMissingHint: "Add this provider key in .env first.",
    estimate: "Estimate",
    easyLocalReason: "Private and free",
    easyVisionReason: "Good for files/images",
    easyCloudReason: "Stronger cloud answer",
    recommendationTitle: "4 recommended models",
    recommendationHint: "Grouped by task type. Cost is an estimate from token pricing.",
    recLocal: "Default local",
    recFile: "Files/images",
    recCode: "Code",
    recLong: "Long document",
    recQuality: "Higher quality",
    recFastLocal: "Fast local",
    groups: {
      recommended: "Recommended",
      local: "Local",
      cloud: "Cloud",
      cheap: "Cheap",
      long: "Long context",
      reasoning: "Reasoning",
      code: "Code",
      vision: "Vision",
      all: "All",
    },
  },
  search: {
    off: "Search off",
    auto: "Local context first",
    always: "Web search",
  },
  chat: {
    emptyTitle: "What are we working on?",
    emptyBody: "This workspace is ready. Choose a model, attach files, or open Context & Files.",
    assistantThinking: "Workbench is thinking",
    preparing: "Workbench is preparing your answer",
    attachFile: "Attach file",
    placeholder: "Ask anything",
    send: "Send",
    stop: "Stop",
    dropFiles: "Drop files to attach them to this message.",
    visionSwitch: "This image needs a vision model. AIWS will switch to Gemini Flash-Lite before sending.",
    tablePrompt: "Analyze this pasted table.",
    tablePastePlaceholder: "Paste cells from Excel, Numbers, Sheets, or any tab-separated table",
    openTools: "Open input tools",
    tools: {
      attach: "Add photos or files",
      table: "Add table",
      image: "Create image",
      web: "Web search",
      more: "More",
      addTable: "Add table",
      cancel: "Cancel",
    },
    quickPrompts: ["Describe an image", "Summarize a document", "Organize tasks", "Help me write"],
  },
  chatHeader: {
    chats: "Chats",
    workspace: "Workspace",
    privateChat: "Private chat",
    projectMemory: "Project memory",
    files: "files",
    goalSet: "Goal set",
    close: "Close",
  },
  titleEdit: {
    save: "Save",
    cancel: "Cancel",
    rename: "Rename",
    saved: "Saved",
    error: "Could not change title.",
  },
  cloudConfirm: {
    titleSuffix: "is a cloud AI model.",
    body: "The privacy manifest for this request will record exactly what leaves AIWS before the cloud call completes.",
    providerModel: "Provider/model",
    userMessage: "User message",
    included: "included",
    attachedFile: "Attached file",
    fileIncluded: "computed file context or vision/file input",
    none: "none",
    estimatedCost: "Estimated cost",
    useOnce: "Use once",
    keepUsing: "Keep using this model",
    cancel: "Cancel",
  },
  attachments: {
    sentImage: "Sent as image input",
    needsVision: "Needs vision model",
    readText: "Read as text",
    remove: "Remove",
  },
  project: {
    memory: "Project Memory",
    recipeStatus: "Recipe Status",
    artifacts: "Artifacts",
  },
  projectDashboard: {
    eyebrow: "Project Workbench",
    operatingEyebrow: "Operating Model",
    operatingTitle: "Folder to Manifest to Workflow Apps to Artifacts",
    operatingBody: "This project is treated as a configurable workbench, not a chat folder. aiws.yaml decides which files are context, which Workflow Apps can run, and which panels explain the outputs.",
    operatingSteps: ["Project folder", "aiws.yaml", "Workflow app registry", "Run timeline", "Artifacts"],
    memoryEyebrow: "Project Memory",
    chatHistory: "Project chat history",
    chats: "chats",
    noChats: "No chats in this project yet. Start a project chat below and it will appear here.",
    actionsEyebrow: "Workflow Apps",
    projectActions: "Project Workflow Apps",
    panelRegistry: "Panel Registry",
    actionKinds: "App Kinds",
    recipesTitle: "Ready and planned recipes",
    noRecipes: "Import aiws.yaml to show each command as Ready, Partial, Planned, or Broken.",
    architectureEyebrow: "Configurable Cockpit",
    architectureTitle: "AIWS architecture",
    architecturePreview: "Architecture preview",
    architectureBody: "This diagram is secondary. Runtime truth should come from real run records, logs, artifacts, and planner events.",
    recentRuns: "Recent Runs",
    runHistory: "Run history",
    noRuns: "No run records yet. Execute a Workflow App to leave logs and artifacts here.",
    generatedOutputs: "Generated outputs",
    noArtifacts: "Generated reports, data files, and script outputs are inspectable here.",
    close: "Close",
    couldNotOpen: "Could not open",
    manifestEyebrow: "aiws.yaml Manifest",
    manifestTitle: "Configurable workbench contract",
    loaded: "loaded",
    templateReady: "template-ready",
    actions: "Apps",
    panels: "Panels",
    views: "Views",
    runs: "Runs",
    contextInclude: "Context include",
    noInclude: "No include patterns yet. Add files/**/*.md, data/**/*.csv, or notes/**/*.txt.",
    securityExclusions: "Security exclusions",
    defaultExclusions: ".env, secrets/**, keys/**, browser profiles, and SSH folders stay out of context by policy.",
    agentEyebrow: "Agent Plan Foundation",
    agentTitle: "Controlled automation, not blind execution",
    experimental: "experimental",
    agentBody: "General chat should evolve into a visible plan: goal, approval gates, step events, costs, artifacts, and final report.",
    agentStepRead: "Inspect selected project files",
    agentStepPlan: "Create a plan and identify missing context",
    agentStepSearch: "Search external context when allowed",
    agentStepPython: "Run analysis script in a controlled step",
    agentStepReport: "Write report artifact and summarize next actions",
    approvalRequired: "approval required",
    agentWarning: "File writes, shell, Python, and network steps must remain approval-gated.",
    customApp: "Custom App",
    investmentTitle: "Investment advisor workbench",
    educationOnly: "education only",
    investmentBody: "Upload portfolio CSV files, define ETF/stock interests, fetch market snapshots when approved, and generate a traceable rebalance research report. This is not financial advice.",
    investmentFlow: ["1. Portfolio CSV", "2. Target allocation", "3. Market snapshot", "4. Rebalance deltas", "5. Research report"],
    advisorActions: "Advisor apps",
    marketSnapshot: "Market snapshot",
    report: "Report",
    notRun: "not run",
    ready: "ready",
    pending: "pending",
    customTips: "Tips for building custom Workflow Apps like this",
    customTipItems: [
      "Keep deterministic math in Python scripts and use LLMs only to explain computed facts.",
      "Put market/network steps behind confirmation and write raw responses as artifacts.",
      "Declare expected files and outputs in aiws.yaml so the UI can show what will run.",
      "Separate research summary from decision; AIWS should show scenarios, risks, and assumptions.",
    ],
  },
  starterActions: {
    document_summary: {
      label: "Summarize document",
      category: "Chat Tool",
      description: "Read a PDF, DOCX, TXT, or MD file and produce a structured summary.",
      prompt: "Summarize the attached document structurally. Separate the core claims, important evidence, and follow-up questions.",
    },
    image_explain: {
      label: "Describe image",
      category: "Chat Tool",
      description: "Attach an image and ask the workspace to describe or compare what it sees.",
      prompt: "Describe the attached image. Split the visible elements, important context, and things I should verify.",
    },
    csv_analysis: {
      label: "Analyze table",
      category: "Chat Tool",
      description: "Inspect CSV, Excel, or pasted table columns, key numbers, and possible outliers.",
      prompt: "Profile this table deterministically and summarize the column structure, key figures, possible outliers, and next analysis steps.",
    },
    deep_research: {
      label: "Deep Research",
      category: "Chat Tool",
      description: "Separate local context, web search intent, citations, and follow-up questions.",
      prompt: "Research this question carefully. Separate what came from local files, what needs web verification, sources to check, risks, and next questions.",
    },
  },
};

export const COPY_KO = {
  locale: "ko",
  productName: "AI Workbench Studio",
  shortName: "AIWS",
  tagline: "프로젝트, 파일, 추적 가능한 결과물을 연결하는 로컬 우선 AI 작업실.",
  brandCompact: "Workbench",
  nav: {
    home: "Chat",
    newChat: "새 대화",
    newProject: "새 프로젝트",
    actions: "Workflow App",
    settings: "설정",
    projects: "프로젝트",
    chats: "대화",
    workspace: "작업실",
    oneOffChats: "일회성 대화",
    searchPlaceholder: "대화 제목 검색",
    noSearchResults: "검색 결과가 없습니다.",
  },
  topbar: {
    localFirst: "로컬 우선",
    contextOpen: "Context & Files 닫기",
    contextClosed: "Context & Files 열기",
    modeLabel: "모드",
  },
  home: {
    title: "로컬 AI 작업실",
    askTitle: "AIWS에 질문",
    askSubtitle: "질문 입력. 필요하면 파일 첨부.",
    projectStartHint: "첫 메시지가 프로젝트 대화로 저장됨.",
    subtitle: "질문, 파일, 프로젝트로 시작. 실행과 산출물은 기록됨.",
    workSessionEyebrow: "작업 시작",
    workSessionTitle: "작업 세션 시작",
    workSessionBody: "질문, 파일, 프로젝트 중 선택. 남길 작업은 context, run, artifact로 기록됨.",
    laneAsk: "한 번 묻기",
    laneAskBody: "빠른 답은 채팅.",
    laneFile: "파일에서 시작",
    laneFileBody: "PDF, 이미지, CSV, DOCX, 텍스트 첨부.",
    laneFileReady: "파일 첨부됨. 도구 선택.",
    laneProject: "프로젝트 만들기",
    laneProjectBody: "목표, 파일, Workflow App, 실행, 산출물 묶음.",
    factActions: "개 도구",
    factRuns: "개 저장된 실행",
    factArtifacts: "개 산출물",
    quickActions: "Chat Tool",
    quickActionsHint: "일회성은 채팅. 반복 작업은 프로젝트 Workflow App.",
    recentRuns: "최근 작업",
    recentArtifacts: "최근 산출물",
    artifacts: "산출물",
    configure: "설정",
    useInput: "첨부 파일 사용",
    prepareBrief: "내용 작성",
    createArtifact: "도구 실행",
    createPrompt: "작업 지시 만들기",
    creating: "생성 중",
    notAvailable: "지원 예정",
    needsFile: "파일 필요",
    ready: "준비됨",
    readyToRun: "실행 가능.",
    openTable: "표 열기",
    workbenchOutputs: "결과물",
    hintCreateTitle: "Workbench 결과물 만들기",
    hintCreateBody: "문서, 이미지, CSV, 코드 작업 먼저 시작 가능.",
    hintInspectTitle: "작업과 산출물 확인",
    hintInspectBody: "입력, 상태, 로그, 산출물 같이 남김.",
    hintPromoteTitle: "반복 작업으로 승격",
    hintPromoteBody: "쓸만한 흐름은 프로젝트/Workflow App으로 저장.",
    attachRequired: "파일 먼저 첨부.",
    codexBriefRequired: "상황과 목표 필요.",
    codexBriefHint: "상황, 관련 파일, 완료 기준 입력.",
    runBeforeProject: "입력 하나로 도구 실행",
    runHistory: "작업 기록",
    starterEmpty: "산출물이나 Codex 작업지시를 만들면 Plan, Log, 결과가 여기에 남습니다.",
    starterEmptyAction: "도구 실행 후 표시.",
    artifactEmpty: "Markdown, CSV, JSON 결과물이 여기에 표시됨.",
    artifactEmptyAction: "파일 생성 후 표시.",
  },
  table: {
    eyebrow: "표 작업대",
    title: "CSV, Excel, 붙여넣은 표 분석",
    emptyDrop: "CSV/XLS/XLSX 드롭, 파일 선택, 표 붙여넣기",
    pastedHint: "스프레드시트 셀 붙여넣기 → 임시 CSV 첨부 + 미리보기.",
    chooseFile: "파일 선택",
    analyze: "표 분석",
    analyzing: "분석 중...",
    close: "닫기",
    pastePlaceholder: "Excel, Numbers, Sheets 표 붙여넣기",
    noPreview: "아직 미리보기가 없습니다.",
    noPreviewHint: "CSV/붙여넣은 표는 즉시 미리보기. XLS/XLSX는 실행 때 분석.",
  },
  catalog: {
    title: "Workflow App & Chat Tool",
    eyebrow: "작업대 카탈로그",
    body: "Chat Tool은 대화 안에서 한 번 호출하는 도구입니다. Workflow App은 aiws.yaml, 실행 기록, 산출물로 반복 실행하는 프로젝트 앱입니다.",
    tools: "Chat Tool",
    toolsBody: "파일, 표, 웹 승인과 함께 한 번 사용.",
    apps: "Workflow App",
    appsBody: "반복되는 일은 프로젝트 안에 설치하거나 설정해서 씁니다.",
    recentRuns: "최근 실행",
    recommendedProjects: "추천 연결 프로젝트",
    input: "입력",
    output: "출력",
    scope: "구분",
    viewer: "뷰어",
    oneOffTool: "일회성 Chat Tool",
    workflowApp: "반복 Workflow App",
    answerViewer: "채팅 답변",
    openTool: "도구 열기",
    connectProject: "프로젝트 연결",
    noRuns: "최근 실행 없음. 도구/앱 실행 후 표시.",
    investmentTitle: "투자 리밸런싱",
    investmentBody: "포트폴리오 CSV와 ETF/주식 관심 방향을 반복 가능한 리서치/리밸런싱 작업실로 만듭니다.",
    fitnessTitle: "식단 / 운동 플래너",
    fitnessBody: "목표, 기록, 반복 리포트를 다루는 예정된 Workflow App입니다.",
    dataResourceTitle: "Data Resource",
    dataResourceBody: "CSV profile, report, JSON artifact를 프로젝트 사이에서 교환.",
  },
  inspector: {
    title: "Context & Files",
    powerTitle: "Right Inspector",
    emptyPurpose: "대화를 시작하면 이 작업실이 참고하는 파일, 컨텍스트, 목표, 실행 기록, 진단 정보가 여기에 정리됩니다.",
    currentContext: "현재 컨텍스트",
    tabs: {
      context: "Context",
      files: "Files",
      memory: "Memory",
      runs: "Runs",
      artifacts: "Artifacts",
      diagnostics: "Diagnostics",
    },
    diagnosticsWarning: "공개 터널이 활성화되어 있습니다. 인증 없이 diagnostics를 노출하지 마세요.",
    factChunks: "chunks",
    factFiles: "files",
    factRuns: "runs",
    factArtifacts: "artifacts",
    includedChunks: "포함된 검색 chunk",
    currentTask: "현재 작업",
    local: "로컬",
    cloud: "클라우드",
    files: "파일",
    receipts: "영수증",
    calls: "호출",
    nextActions: "다음 작업",
    attachOrPaste: "입력 파일 추가 또는 표 붙여넣기",
    runAction: "표/문서 도구 실행",
    saveUsefulAnswer: "쓸만한 답변을 결과물로 저장",
    sendToCreateReceipt: "메시지를 보내 context receipt 만들기",
    promoteTitle: "프로젝트로 승격",
    promoteBody: "이 대화, 파일, receipt, 앞으로 만들 결과물을 새 private 프로젝트로 옮깁니다.",
    promote: "승격",
    promoting: "승격 중...",
    workSession: "WorkSession",
  },
  messageActions: {
    saveArtifact: "결과물로 저장",
    saving: "저장 중...",
    saved: "저장됨",
    download: "답변 다운로드",
  },
  settings: {
    title: "작업실 설정",
    close: "닫기",
    savedMessages: "저장 메시지",
    aiRequests: "AI 요청",
    monthlyApiCost: "이번 달 API 비용",
    profile: "프로필",
    avatar: "프로필 사진",
    name: "이름",
    age: "나이",
    role: "직업 / 역할",
    language: "언어",
    personalContext: "개인 컨텍스트",
    situation: "상황 / 대화 컨텍스트",
    addMemory: "기억에 추가",
    memoryPlaceholder: "Workbench가 앞으로 기억하면 좋은 내용을 적어주세요.",
    interface: "인터페이스",
    uiMode: "사용 모드",
    easyMode: "Easy Mode - 쉬운 화면",
    powerMode: "Power Mode - 운영자 화면",
    modeHelp: "Easy는 모델 선택과 파일 첨부는 그대로 두고 운영자 로그를 숨깁니다. Power는 실행 경로, 비용, prompt, runtime을 확인하는 화면입니다.",
    saveProfile: "프로필 저장",
    monthlyApiForecast: "이번 달 예측",
    allAccountForecast: "전체 계정 예측",
  },
  modelPicker: {
    title: "AI 모델 선택",
    easyTitle: "모델 선택",
    easyHint: "추천, 로컬, 클라우드만 고르면 됨.",
    showDetails: "상세 설정",
    hideDetails: "간단히 보기",
    selected: "사용 중",
    local: "로컬",
    localMac: "로컬 Mac",
    cloudAi: "클라우드 AI",
    freeLocal: "무료 · 로컬",
    paidCloud: "유료 · 클라우드",
    keyReady: "키 연결됨",
    keyMissing: "키 없음",
    keyMissingHint: ".env에 provider 키를 먼저 넣어야 함.",
    estimate: "예상 비용",
    easyLocalReason: "비공개 · 무료",
    easyVisionReason: "파일/이미지용",
    easyCloudReason: "더 강한 클라우드 답변",
    recommendationTitle: "추천 모델 4개",
    recommendationHint: "작업 종류별 추천. 비용은 토큰 단가 기반 예측.",
    recLocal: "기본 로컬",
    recFile: "파일/이미지",
    recCode: "코드",
    recLong: "긴 문서",
    recQuality: "고품질",
    recFastLocal: "빠른 로컬",
    groups: {
      recommended: "추천",
      local: "로컬",
      cloud: "클라우드",
      cheap: "저비용",
      long: "긴 문서",
      reasoning: "추론",
      code: "코드",
      vision: "이미지",
      all: "전체",
    },
  },
  search: {
    off: "검색 끔",
    auto: "로컬 컨텍스트 우선",
    always: "웹 검색",
  },
  chat: {
    emptyTitle: "무엇을 도와드릴까요?",
    emptyBody: "모델 선택, 파일 첨부, 질문 입력.",
    assistantThinking: "생각 중",
    preparing: "답변 준비 중",
    attachFile: "파일 추가",
    placeholder: "무엇이든 물어보세요",
    send: "보내기",
    stop: "중지",
    dropFiles: "파일 드롭 → 메시지에 첨부.",
    visionSwitch: "이미지는 비전 모델 필요. Gemini Flash-Lite로 전환됨.",
    tablePrompt: "이 붙여넣은 표를 분석해줘.",
    tablePastePlaceholder: "Excel, Numbers, Sheets 표 붙여넣기",
    openTools: "입력 도구 열기",
    tools: {
      attach: "사진 및 파일 추가",
      table: "표 추가",
      image: "이미지 만들기",
      web: "웹 검색",
      more: "더 보기",
      addTable: "표 추가",
      cancel: "취소",
    },
    quickPrompts: ["이미지 설명", "문서 요약", "할 일 정리", "글쓰기 돕기"],
  },
  chatHeader: {
    chats: "대화",
    workspace: "작업실",
    privateChat: "개인 대화",
    projectMemory: "프로젝트 메모리",
    files: "개 파일",
    goalSet: "목표 설정됨",
    close: "닫기",
  },
  titleEdit: {
    save: "저장",
    cancel: "취소",
    rename: "이름 변경",
    saved: "저장됨",
    error: "제목을 변경하지 못했습니다.",
  },
  cloudConfirm: {
    titleSuffix: "클라우드 AI 모델입니다.",
    body: "클라우드로 나가는 내용 기록 후 호출.",
    providerModel: "제공자/모델",
    userMessage: "사용자 메시지",
    included: "포함",
    attachedFile: "첨부 파일",
    fileIncluded: "계산된 파일 컨텍스트 또는 비전/파일 입력",
    none: "없음",
    estimatedCost: "예상 비용",
    useOnce: "이번만 사용",
    keepUsing: "이 모델 계속 사용",
    cancel: "취소",
  },
  attachments: {
    sentImage: "이미지 입력으로 전송",
    needsVision: "비전 모델 필요",
    readText: "텍스트로 읽음",
    remove: "삭제",
  },
  project: {
    memory: "프로젝트 메모리",
    recipeStatus: "레시피 상태",
    artifacts: "산출물",
  },
  projectDashboard: {
    eyebrow: "프로젝트 작업대",
    operatingEyebrow: "작동 구조",
    operatingTitle: "폴더에서 manifest, Workflow App, artifact까지",
    operatingBody: "대화 폴더가 아니라 설정 가능한 작업대. aiws.yaml이 파일, Workflow App, 패널을 정함.",
    operatingSteps: ["프로젝트 폴더", "aiws.yaml", "Workflow App 레지스트리", "실행 타임라인", "산출물"],
    memoryEyebrow: "프로젝트 메모리",
    chatHistory: "프로젝트 대화 기록",
    chats: "개 대화",
    noChats: "대화 없음. 프로젝트 대화 시작 후 표시.",
    actionsEyebrow: "Workflow App",
    projectActions: "프로젝트 Workflow App",
    panelRegistry: "패널 레지스트리",
    actionKinds: "앱 종류",
    recipesTitle: "준비됨 / 예정된 레시피",
    noRecipes: "aiws.yaml 가져오면 상태 표시.",
    architectureEyebrow: "설정 가능한 작업대",
    architectureTitle: "AIWS 아키텍처",
    architecturePreview: "아키텍처 미리보기",
    architectureBody: "보조 다이어그램. 실제 상태는 run, 로그, 산출물, planner 이벤트 기준.",
    recentRuns: "최근 실행",
    runHistory: "실행 기록",
    noRuns: "run 기록 없음. Workflow App 실행 후 로그와 산출물 생성.",
    generatedOutputs: "생성된 결과물",
    noArtifacts: "보고서, 데이터 파일, 스크립트 출력 없음.",
    close: "닫기",
    couldNotOpen: "열 수 없음",
    manifestEyebrow: "aiws.yaml Manifest",
    manifestTitle: "설정 가능한 작업대 계약",
    loaded: "불러옴",
    templateReady: "템플릿 준비됨",
    actions: "앱",
    panels: "패널",
    views: "뷰",
    runs: "실행",
    contextInclude: "포함할 컨텍스트",
    noInclude: "include 패턴 없음. 예: files/**/*.md, data/**/*.csv",
    securityExclusions: "보안 제외",
    defaultExclusions: ".env, secrets/**, keys/**, 브라우저 프로필, SSH 폴더 제외.",
    agentEyebrow: "Agent Plan 기반",
    agentTitle: "무작정 실행하지 않는 제어형 자동화",
    experimental: "실험적",
    agentBody: "일반 대화도 목표, 승인, step, 비용, 산출물이 보이는 plan으로 발전.",
    agentStepRead: "선택한 프로젝트 파일 확인",
    agentStepPlan: "계획 생성 및 부족한 컨텍스트 식별",
    agentStepSearch: "허용된 경우 외부 컨텍스트 검색",
    agentStepPython: "제어된 단계에서 분석 스크립트 실행",
    agentStepReport: "보고서 산출물 작성 및 다음 작업 요약",
    approvalRequired: "승인 필요",
    agentWarning: "파일 쓰기, shell, Python, 네트워크는 승인 뒤 실행.",
    customApp: "커스텀 앱",
    investmentTitle: "투자 advisor 작업대",
    educationOnly: "교육용",
    investmentBody: "포트폴리오 CSV, 관심 ETF/주식, 승인된 시장 스냅샷으로 리밸런싱 리서치 보고서 생성. 투자 조언 아님.",
    investmentFlow: ["1. 포트폴리오 CSV", "2. 목표 배분", "3. 시장 스냅샷", "4. 리밸런싱 차이", "5. 리서치 보고서"],
    advisorActions: "Advisor 앱",
    marketSnapshot: "시장 스냅샷",
    report: "보고서",
    notRun: "미실행",
    ready: "준비됨",
    pending: "대기 중",
    customTips: "이런 커스텀 Workflow App을 만들 때의 팁",
    customTipItems: [
      "계산은 Python에서 deterministic 처리. LLM은 계산 사실 설명만.",
      "시장/네트워크 단계는 승인 뒤. 원본 응답은 artifact 저장.",
      "입력 파일과 출력물을 aiws.yaml에 선언.",
      "리서치 요약과 의사결정 분리. 시나리오, 위험, 가정 표시.",
    ],
  },
  starterActions: {
    document_summary: {
      label: "문서 요약",
      category: "Chat Tool",
      description: "PDF, DOCX, TXT, MD 파일을 읽고 구조화된 요약을 만듭니다.",
      prompt: "첨부한 문서를 구조적으로 요약해줘. 핵심 주장, 중요한 근거, 후속 질문을 나눠서 정리해줘.",
    },
    image_explain: {
      label: "이미지 설명",
      category: "Chat Tool",
      description: "이미지를 첨부하면 보이는 내용과 확인할 점을 정리합니다.",
      prompt: "첨부한 이미지를 설명해줘. 보이는 요소, 중요한 맥락, 사람이 확인해야 할 점을 나눠서 정리해줘.",
    },
    csv_analysis: {
      label: "표 분석",
      category: "Chat Tool",
      description: "CSV, Excel, 붙여넣은 표의 컬럼, 주요 숫자, 결측치와 다음 분석 방향을 확인합니다.",
      prompt: "이 표를 deterministic profile로 분석하고 컬럼 구조, 주요 수치, 결측치, 이상치 가능성, 다음 분석 단계를 정리해줘.",
    },
    deep_research: {
      label: "심층 리서치",
      category: "Chat Tool",
      description: "로컬 컨텍스트, 웹 검색 의도, 출처, 후속 질문을 분리해 정리합니다.",
      prompt: "이 질문을 신중하게 리서치해줘. 로컬 파일에서 온 내용, 웹 검증이 필요한 내용, 확인할 출처, 리스크, 다음 질문을 나눠줘.",
    },
  },
};

type CopyNode = Record<string, unknown>;

function mergeCopy(base: CopyNode, override: CopyNode): CopyNode {
  const output = { ...base };
  Object.entries(override || {}).forEach(([key, value]) => {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      output[key] = mergeCopy((base[key] || {}) as CopyNode, value as CopyNode);
    } else {
      output[key] = value;
    }
  });
  return output;
}

export function copyForLocale(locale = "en") {
  return String(locale || "").toLowerCase().startsWith("ko")
    ? mergeCopy(COPY_EN, COPY_KO) as typeof COPY_EN
    : COPY_EN;
}

export function copyForAccount(account?: { profile?: { language?: string } } | null) {
  return copyForLocale(account?.profile?.language || "en");
}

export const COPY = COPY_EN;
