/**
 * AUTO-GENERATED by scripts/gen-api-inventory.mjs — DO NOT EDIT BY HAND.
 * The complete HTTP API surface scanned from apps/server/src/routes.
 * Re-run `node scripts/gen-api-inventory.mjs` after changing routes.
 */
export interface ApiEndpoint {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  domain: string;
  params?: string;
  query?: string;
  body?: string;
}

export const API_ENDPOINTS: ApiEndpoint[] = [
  {
    "method": "PUT",
    "path": "/api/account/context",
    "domain": "account"
  },
  {
    "method": "GET",
    "path": "/api/account/limits",
    "domain": "account"
  },
  {
    "method": "PUT",
    "path": "/api/account/locale",
    "domain": "account"
  },
  {
    "method": "PUT",
    "path": "/api/account/mode",
    "domain": "account"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/action-defs",
    "domain": "actions",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/actions",
    "domain": "actions",
    "params": "{id: string}"
  },
  {
    "method": "PUT",
    "path": "/api/workspaces/:id/actions",
    "domain": "actions",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/actions/:actionId/run",
    "domain": "actions",
    "params": "{id: string; actionId: string}"
  },
  {
    "method": "GET",
    "path": "/api/alerts",
    "domain": "alerts"
  },
  {
    "method": "DELETE",
    "path": "/api/alerts/:id",
    "domain": "alerts",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/alerts/:id/read",
    "domain": "alerts",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/alerts/read-all",
    "domain": "alerts"
  },
  {
    "method": "GET",
    "path": "/api/attempts/:id",
    "domain": "attempts",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/attempts/:id/abandon",
    "domain": "attempts",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/attempts/:id/apply",
    "domain": "attempts",
    "params": "{id: string}",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/chats/:chatId/attempts",
    "domain": "attempts",
    "params": "{chatId: string}"
  },
  {
    "method": "GET",
    "path": "/api/chats/:chatId/open-attempt",
    "domain": "attempts",
    "params": "{chatId: string}"
  },
  {
    "method": "POST",
    "path": "/api/auth/guest",
    "domain": "auth"
  },
  {
    "method": "POST",
    "path": "/api/auth/login",
    "domain": "auth"
  },
  {
    "method": "POST",
    "path": "/api/auth/logout",
    "domain": "auth"
  },
  {
    "method": "GET",
    "path": "/api/auth/me",
    "domain": "auth"
  },
  {
    "method": "POST",
    "path": "/api/auth/reset",
    "domain": "auth"
  },
  {
    "method": "GET",
    "path": "/api/chats",
    "domain": "chat"
  },
  {
    "method": "POST",
    "path": "/api/chats",
    "domain": "chat",
    "body": "unknown"
  },
  {
    "method": "DELETE",
    "path": "/api/chats/:id",
    "domain": "chat",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/chats/:id",
    "domain": "chat",
    "params": "{id: string}"
  },
  {
    "method": "PATCH",
    "path": "/api/chats/:id",
    "domain": "chat",
    "params": "{id: string}",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/chats/:id/active",
    "domain": "chat",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/chats/:id/messages",
    "domain": "chat",
    "params": "{id: string}",
    "body": "unknown"
  },
  {
    "method": "POST",
    "path": "/api/chats/:id/messages/:messageId/regenerate",
    "domain": "chat",
    "params": "{id: string; messageId: string}",
    "body": "unknown"
  },
  {
    "method": "POST",
    "path": "/api/chats/:id/stop",
    "domain": "chat",
    "params": "{id: string}"
  },
  {
    "method": "DELETE",
    "path": "/api/chats/empty",
    "domain": "chat",
    "query": "{olderHours?: string}"
  },
  {
    "method": "GET",
    "path": "/api/uploads/:id",
    "domain": "chat",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/compare",
    "domain": "compare",
    "body": "unknown"
  },
  {
    "method": "POST",
    "path": "/api/eval-cases/promote",
    "domain": "evalCases"
  },
  {
    "method": "POST",
    "path": "/api/files/extract",
    "domain": "files",
    "body": "{workspaceId?: string; path?: string; chunked?: boolean; chunkChars?: number; backend?: \"auto\" | \"markitdown\" | \"pymupdf\"}"
  },
  {
    "method": "GET",
    "path": "/api/files/markdown-cached",
    "domain": "files",
    "query": "{workspaceId?: string; path?: string}"
  },
  {
    "method": "GET",
    "path": "/api/files/markitdown-status",
    "domain": "files"
  },
  {
    "method": "GET",
    "path": "/api/files/pdf-screenshot",
    "domain": "files",
    "query": "{workspaceId?: string; path?: string; page?: string; scale?: string}"
  },
  {
    "method": "GET",
    "path": "/api/fs/list",
    "domain": "fs",
    "query": "{path?: string}"
  },
  {
    "method": "POST",
    "path": "/api/fs/mkdir",
    "domain": "fs",
    "body": "{parent?: string; name?: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/git/commit",
    "domain": "git",
    "params": "{id: string}",
    "body": "{message?: string; paths?: string[]}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/git/diff",
    "domain": "git",
    "params": "{id: string}",
    "query": "{path?: string; staged?: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/git/status",
    "domain": "git",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/healthz",
    "domain": "health"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/hooks",
    "domain": "hooks",
    "params": "{id: string}"
  },
  {
    "method": "PUT",
    "path": "/api/workspaces/:id/hooks",
    "domain": "hooks",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/hooks/:hookId/log",
    "domain": "hooks",
    "params": "{id: string; hookId: string}"
  },
  {
    "method": "GET",
    "path": "/api/market/calendar",
    "domain": "marketData",
    "query": "{symbols?: string}"
  },
  {
    "method": "GET",
    "path": "/api/market/dividends",
    "domain": "marketData",
    "query": "{symbol?: string; range?: string}"
  },
  {
    "method": "GET",
    "path": "/api/market/fx",
    "domain": "marketData",
    "query": "{base?: string; symbols?: string}"
  },
  {
    "method": "GET",
    "path": "/api/market/history",
    "domain": "marketData",
    "query": "{symbol?: string; range?: string; interval?: string}"
  },
  {
    "method": "GET",
    "path": "/api/market/news",
    "domain": "marketData",
    "query": "{symbol?: string; max?: string}"
  },
  {
    "method": "GET",
    "path": "/api/market/normalize",
    "domain": "marketData",
    "query": "{symbol?: string}"
  },
  {
    "method": "GET",
    "path": "/api/market/quotes",
    "domain": "marketData",
    "query": "{symbols?: string; detailed?: string}"
  },
  {
    "method": "GET",
    "path": "/api/mcp-servers",
    "domain": "mcp"
  },
  {
    "method": "POST",
    "path": "/api/mcp-servers",
    "domain": "mcp"
  },
  {
    "method": "DELETE",
    "path": "/api/mcp-servers/:id",
    "domain": "mcp",
    "params": "{id: string}"
  },
  {
    "method": "PATCH",
    "path": "/api/mcp-servers/:id",
    "domain": "mcp",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/mcp-servers/:id/test",
    "domain": "mcp",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/mcp-servers/:id/tools",
    "domain": "mcp",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/memory",
    "domain": "memory",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/memory",
    "domain": "memory",
    "params": "{id: string}"
  },
  {
    "method": "DELETE",
    "path": "/api/workspaces/:id/memory/:memId",
    "domain": "memory",
    "params": "{id: string; memId: string}"
  },
  {
    "method": "DELETE",
    "path": "/api/providers/:id/key",
    "domain": "providers",
    "params": "{id: string}"
  },
  {
    "method": "PUT",
    "path": "/api/providers/:id/key",
    "domain": "providers",
    "params": "{id: string}",
    "body": "{key?: string}"
  },
  {
    "method": "GET",
    "path": "/api/providers/status",
    "domain": "providers"
  },
  {
    "method": "GET",
    "path": "/api/reports",
    "domain": "reports",
    "query": "{status?: string}"
  },
  {
    "method": "POST",
    "path": "/api/reports",
    "domain": "reports"
  },
  {
    "method": "GET",
    "path": "/api/reports/:id",
    "domain": "reports",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/reports/:id/decision",
    "domain": "reports",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/runs",
    "domain": "runs",
    "query": "{workspaceId?: string}"
  },
  {
    "method": "POST",
    "path": "/api/runs",
    "domain": "runs"
  },
  {
    "method": "GET",
    "path": "/api/runs/:id",
    "domain": "runs",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/runs/:id/brief",
    "domain": "runs",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/runs/:id/context",
    "domain": "runs",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/runs/:id/context",
    "domain": "runs",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/runs/:id/diff",
    "domain": "runs",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/runs/:id/evidence",
    "domain": "runs",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/runs/:runId/staged",
    "domain": "runs",
    "params": "{runId: string}"
  },
  {
    "method": "POST",
    "path": "/api/runs/:runId/staged/apply",
    "domain": "runs",
    "params": "{runId: string}",
    "body": "unknown"
  },
  {
    "method": "POST",
    "path": "/api/runs/:runId/staged/discard",
    "domain": "runs",
    "params": "{runId: string}"
  },
  {
    "method": "DELETE",
    "path": "/api/schedules/:id",
    "domain": "schedules",
    "params": "{id: string}"
  },
  {
    "method": "PATCH",
    "path": "/api/schedules/:id",
    "domain": "schedules",
    "params": "{id: string}",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:workspaceId/schedules",
    "domain": "schedules",
    "params": "{workspaceId: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:workspaceId/schedules",
    "domain": "schedules",
    "params": "{workspaceId: string}",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/scripts",
    "domain": "scripts",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/scripts/:name",
    "domain": "scripts",
    "params": "{id: string; name: string}"
  },
  {
    "method": "PUT",
    "path": "/api/workspaces/:id/scripts/:name",
    "domain": "scripts",
    "params": "{id: string; name: string}",
    "body": "{content: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/scripts/:name/run",
    "domain": "scripts",
    "params": "{id: string; name: string}"
  },
  {
    "method": "POST",
    "path": "/api/images/search",
    "domain": "search",
    "body": "unknown"
  },
  {
    "method": "POST",
    "path": "/api/search",
    "domain": "search",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/settings",
    "domain": "settings"
  },
  {
    "method": "PUT",
    "path": "/api/settings",
    "domain": "settings"
  },
  {
    "method": "GET",
    "path": "/api/skills",
    "domain": "skills"
  },
  {
    "method": "POST",
    "path": "/api/skills",
    "domain": "skills",
    "body": "unknown"
  },
  {
    "method": "DELETE",
    "path": "/api/skills/:id",
    "domain": "skills",
    "params": "{id: string}"
  },
  {
    "method": "PATCH",
    "path": "/api/skills/:id",
    "domain": "skills",
    "params": "{id: string}",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/file",
    "domain": "surface",
    "params": "{id: string}",
    "query": "{path?: string}"
  },
  {
    "method": "PUT",
    "path": "/api/workspaces/:id/file",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{path?: string; content?: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/file/create",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{path?: string; content?: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/file/stage",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{path?: string; content?: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/surface",
    "domain": "surface",
    "params": "{id: string}"
  },
  {
    "method": "PUT",
    "path": "/api/workspaces/:id/surface",
    "domain": "surface",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/surface/ask",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{prompt?: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/surface/build",
    "domain": "surface",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/surface/folder",
    "domain": "surface",
    "params": "{id: string}"
  },
  {
    "method": "DELETE",
    "path": "/api/workspaces/:id/surface/folder/file",
    "domain": "surface",
    "params": "{id: string}",
    "query": "{path?: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/surface/folder/file",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{path?: string; content?: string}"
  },
  {
    "method": "PUT",
    "path": "/api/workspaces/:id/surface/folder/file",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{path?: string; content?: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/surface/search",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{query?: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/surface/state",
    "domain": "surface",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/surface/state",
    "domain": "surface",
    "params": "{id: string}",
    "body": "{state?: unknown}"
  },
  {
    "method": "GET",
    "path": "/api/surface/:workspaceId/bundle.js",
    "domain": "surfaceHost",
    "params": "{workspaceId: string}"
  },
  {
    "method": "GET",
    "path": "/api/surface/:workspaceId/host",
    "domain": "surfaceHost",
    "params": "{workspaceId: string}",
    "query": "{theme?: string}"
  },
  {
    "method": "GET",
    "path": "/api/templates",
    "domain": "templates"
  },
  {
    "method": "GET",
    "path": "/api/templates/:id",
    "domain": "templates",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/terminal",
    "domain": "terminal",
    "params": "{id: string}"
  },
  {
    "method": "DELETE",
    "path": "/api/triggers/:id",
    "domain": "triggers",
    "params": "{id: string}"
  },
  {
    "method": "POST",
    "path": "/api/triggers/:secret",
    "domain": "triggers",
    "params": "{secret: string}",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:workspaceId/triggers",
    "domain": "triggers",
    "params": "{workspaceId: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:workspaceId/triggers",
    "domain": "triggers",
    "params": "{workspaceId: string}",
    "body": "unknown"
  },
  {
    "method": "GET",
    "path": "/api/usage",
    "domain": "usage"
  },
  {
    "method": "GET",
    "path": "/api/workspaces",
    "domain": "workspaces"
  },
  {
    "method": "POST",
    "path": "/api/workspaces",
    "domain": "workspaces"
  },
  {
    "method": "DELETE",
    "path": "/api/workspaces/:id",
    "domain": "workspaces",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id",
    "domain": "workspaces",
    "params": "{id: string}"
  },
  {
    "method": "PATCH",
    "path": "/api/workspaces/:id",
    "domain": "workspaces",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/context",
    "domain": "workspaces",
    "params": "{id: string}"
  },
  {
    "method": "PUT",
    "path": "/api/workspaces/:id/context",
    "domain": "workspaces",
    "params": "{id: string}",
    "body": "{context?: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/events",
    "domain": "workspaces",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/export",
    "domain": "workspaces",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/history",
    "domain": "workspaces",
    "params": "{id: string}",
    "query": "{limit?: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/history/:sha",
    "domain": "workspaces",
    "params": "{id: string; sha: string}"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/history/rewind",
    "domain": "workspaces",
    "params": "{id: string}",
    "body": "unknown"
  },
  {
    "method": "POST",
    "path": "/api/workspaces/:id/scan",
    "domain": "workspaces",
    "params": "{id: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/search",
    "domain": "workspaces",
    "params": "{id: string}",
    "query": "{q?: string; topK?: string}"
  },
  {
    "method": "GET",
    "path": "/api/workspaces/:id/snapshot",
    "domain": "workspaces",
    "params": "{id: string}"
  }
];

/** Domain → description, sourced from the route registry (routes/registry.ts). */
export const DOMAIN_DESCRIPTIONS: Record<string, string> = {
  "auth": "Login / logout / session — and the local-vs-remote access model (loopback = admin).",
  "workspaces": "Create, scan, configure, and snapshot workspaces — the folder-rooted unit everything hangs off.",
  "templates": "Run templates — turn files into a structured output.",
  "runs": "Template/agent runs — context pick, brief, evidence, staged diff, apply, and history rewind.",
  "settings": "The active AI provider + model and other server-wide settings.",
  "fs": "Browse the host filesystem (the folder picker when creating a workspace). Local-only.",
  "usage": "Token usage + per-account limits.",
  "scripts": "Workspace scripts in .ariadne/scripts/ — list, read, run.",
  "search": "RAG search over a workspace's indexed chunks; cross-workspace content search.",
  "chat": "Conversations + streaming assistant replies (SSE). The send pipeline: triage → retrieval → provider → metering.",
  "compare": "Run one prompt against N models concurrently (cross-vendor compare).",
  "providers": "Configured AI providers and their reachability (keys, local models).",
  "account": "The signed-in account: profile, locale, UI mode (simple/standard), saved context.",
  "surface": "User-authored custom screens (.ariadne/surface.tsx) — bundle, build, RAG, ask, persisted state.",
  "git": "The workspace's own git repo: status, per-file diff, and selective commit. Local-only commit.",
  "terminal": "A real PTY shell in the workspace root over a WebSocket. Local-only.",
  "actions": "Workspace actions.yaml — tools the agent planner may use (run_script, read_file, …).",
  "triggers": "Event webhooks — POST /api/triggers/:secret fires a run; the secret IS the auth.",
  "alerts": "In-app notifications (the bell).",
  "reports": "User-filed problem reports + the admin review queue.",
  "evalCases": "RAG eval cases for the retrieval harness.",
  "memory": "Per-workspace agent memory — facts injected into context.",
  "mcp": "Model Context Protocol servers — register external tools the agent can call.",
  "hooks": "Per-workspace commands that fire on events (staged_apply, post_scan, memory_added).",
  "marketData": "Market-data helpers used by the portfolio example project.",
  "files": "Read workspace files + binary-document previews (markdown cache, PDF page images).",
  "skills": "Reusable skill definitions surfaced to the agent + the composer.",
  "schedules": "Scheduled runs (the scheduler ticks every 60s) — list, create, run-now.",
  "attempts": "Parallel attempts of a run (fan-out) + their diffs."
};
