from pathlib import Path
from typing import Any, Protocol


class FileStore(Protocol):
    def read_json(self, path: Path) -> dict[str, Any]: ...

    def write_json(self, path: Path, data: dict[str, Any]) -> None: ...

    def append_jsonl(self, path: Path, record: dict[str, Any]) -> None: ...

    def read_jsonl(self, path: Path) -> list[dict[str, Any]]: ...
