from typing import Protocol

from aiws.domain.models import Message, Project, Session, User, Workspace
from aiws.domain.runs import Run


class WorkspaceRepository(Protocol):
    def save(self, workspace: Workspace) -> None: ...

    def get(self) -> Workspace: ...


class UserRepository(Protocol):
    def save_many(self, users: tuple[User, ...]) -> None: ...

    def list(self) -> tuple[User, ...]: ...


class ProjectRepository(Protocol):
    def save(self, project: Project) -> None: ...

    def get(self, project_path: str) -> Project: ...

    def list(self) -> tuple[Project, ...]: ...


class SessionRepository(Protocol):
    def save(self, session: Session) -> None: ...

    def get(self, project_path: str, session_id: str) -> Session: ...

    def list_for_project(self, project_path: str) -> tuple[Session, ...]: ...


class MessageRepository(Protocol):
    def append(self, project_path: str, session_slug: str, message: Message) -> None: ...

    def list_for_session(self, project_path: str, session_slug: str) -> tuple[Message, ...]: ...


class RunRepository(Protocol):
    def save(self, run: Run) -> None: ...

    def get(self, project_path: str, run_id: str) -> Run: ...
