export const COPY_EN = {
  locale: "en",
  productName: "AI Workbench Studio",
  shortName: "AIWS",
  tagline: "Local-first AI workbench for projects, files, and traceable outputs.",
  brandCompact: "Workbench",
  nav: {
    home: "Home",
    newChat: "New Chat",
    newProject: "New Project",
    actions: "Actions",
    projects: "Projects",
    chats: "Chats",
    workspace: "Workspace",
    oneOffChats: "One-off chats",
    searchPlaceholder: "Search chat titles",
    noSearchResults: "No results.",
  },
  topbar: {
    localFirst: "Local-first",
    contextOpen: "Close Context & Files",
    contextClosed: "Open Context & Files",
    modeLabel: "Mode",
  },
  home: {
    title: "Local AI Workbench",
    subtitle: "Start a work session from a question, file, or project. Runs and artifacts stay inspectable.",
    workSessionEyebrow: "Start work",
    workSessionTitle: "Start a work session",
    workSessionBody: "Ask once, start from a file, or create a project workspace. AIWS records the context, run, and artifact when there is something to keep.",
    laneAsk: "Ask once",
    laneAskBody: "Use chat for a quick answer.",
    laneFile: "Start from file",
    laneFileBody: "Attach PDF, image, CSV, DOCX, or text.",
    laneFileReady: "File attached. Choose an action below.",
    laneProject: "Create project",
    laneProjectBody: "Keep goals, files, actions, runs, and artifacts together.",
    factActions: "available actions",
    factRuns: "saved runs",
    factArtifacts: "artifacts",
    quickActions: "Quick Actions",
    quickActionsHint: "Create a projectless output, then save the useful workflow into a project.",
    recentRuns: "Recent Work",
    recentArtifacts: "Recent Artifacts",
    artifacts: "Artifacts",
    configure: "Configure",
    useInput: "Use attached file",
    prepareBrief: "Write brief",
    createArtifact: "Create result",
    createPrompt: "Create brief",
    creating: "Creating",
    notAvailable: "Planned",
    openTable: "Open table",
    workbenchOutputs: "Outputs",
    hintCreateTitle: "Create a Workbench Output",
    hintCreateBody: "Start document, image, CSV, or code work before creating a project.",
    hintInspectTitle: "Inspect Work and Artifacts",
    hintInspectBody: "Each output keeps its input snapshot, status, log, and clickable artifacts.",
    hintPromoteTitle: "Promote repeatable work",
    hintPromoteBody: "Save useful flows into projects, actions, and configurable panels.",
    attachRequired: "Attach a file before creating this artifact.",
    codexBriefRequired: "Describe the situation and desired change before creating a Codex brief.",
    codexBriefHint: "Write the situation first: what changed, which files matter, and what done means.",
    runBeforeProject: "Create from one input",
    runHistory: "Work history",
    starterEmpty: "Create an artifact or Codex brief to keep the plan, log, and output here.",
    starterEmptyAction: "Run history only appears after a real starter action creates a persisted run.",
    artifactEmpty: "Markdown, CSV, JSON, and report outputs appear as clickable objects.",
    artifactEmptyAction: "Artifacts appear after a run writes a real file.",
  },
  table: {
    eyebrow: "Table Workbench",
    title: "Analyze CSV, Excel, or pasted tables",
    emptyDrop: "Drop CSV/XLS/XLSX here, choose a file, or paste table cells below",
    pastedHint: "Copied spreadsheet cells become a temporary CSV attachment and fill the preview table.",
    chooseFile: "Choose file",
    analyze: "Analyze table",
    analyzing: "Analyzing...",
    close: "Close",
    pastePlaceholder: "Paste cells from Excel, Numbers, Sheets, or a tab-separated table",
    noPreview: "No preview yet.",
    noPreviewHint: "CSV and pasted tables preview here. XLS/XLSX files are parsed by the backend when you run analysis.",
  },
  inspector: {
    title: "Context & Files",
    powerTitle: "Right Inspector",
    emptyPurpose: "Start a chat to see the files, context, goals, runs, and diagnostics used by this workspace.",
    currentContext: "Current Context",
    tabs: {
      context: "Context",
      files: "Files",
      memory: "Memory",
      runs: "Runs",
      artifacts: "Artifacts",
      diagnostics: "Diagnostics",
    },
    diagnosticsWarning: "Public tunnel is active. Do not expose diagnostics without authentication.",
    factChunks: "chunks",
    factFiles: "files",
    factRuns: "runs",
    factArtifacts: "artifacts",
    includedChunks: "Included retrieval chunks",
    currentTask: "Current Task",
    local: "Local",
    cloud: "Cloud",
    files: "files",
    receipts: "receipts",
    calls: "calls",
    nextActions: "Next actions",
    attachOrPaste: "Attach or paste an input",
    runAction: "Run table/document action",
    saveUsefulAnswer: "Save useful answer as artifact",
    sendToCreateReceipt: "Send a message to create a receipt",
    promoteTitle: "Promote to project",
    promoteBody: "Move this chat, files, receipts, and future artifacts into a new private project.",
    promote: "Promote",
    promoting: "Promoting...",
    workSession: "WorkSession",
  },
  messageActions: {
    saveArtifact: "Save as artifact",
    saving: "Saving...",
  },
  settings: {
    title: "Workspace Settings",
    close: "Close",
    savedMessages: "Saved messages",
    aiRequests: "AI requests",
    monthlyApiCost: "API cost this month",
    profile: "Profile",
    avatar: "Profile photo",
    name: "Name",
    age: "Age",
    role: "Job / role",
    language: "Language",
    personalContext: "Personal Context",
    situation: "Situation / chat context",
    addMemory: "Add to memory",
    memoryPlaceholder: "Write anything the workbench should remember later.",
    interface: "Interface",
    uiMode: "UI mode",
    easyMode: "Easy Mode - focused workspace",
    powerMode: "Power Mode - diagnostics and execution details",
    modeHelp: "Easy keeps model and file controls visible while hiding operator logs. Power shows execution paths, cost, prompts, and runtime details.",
    saveProfile: "Save profile",
  },
  modelPicker: {
    title: "Select AI Model",
    selected: "selected",
    groups: {
      recommended: "Recommended",
      local: "Local",
      fast: "Fast",
      long: "Long context",
      reasoning: "Reasoning",
      coding: "Coding",
      all: "All",
    },
  },
  search: {
    off: "Search off",
    auto: "Local context first",
    always: "Web search",
  },
  chat: {
    emptyTitle: "What are we working on?",
    emptyBody: "This workspace is ready. Choose a model, attach files, or open Context & Files.",
    assistantThinking: "Workbench is thinking",
    preparing: "Workbench is preparing your answer",
    attachFile: "Attach file",
    placeholder: "Ask anything",
    quickPrompts: ["Describe an image", "Summarize a document", "Organize tasks", "Help me write"],
  },
  project: {
    memory: "Project Memory",
    recipeStatus: "Recipe Status",
    artifacts: "Artifacts",
  },
  starterActions: {
    document_summary: {
      label: "Summarize document",
      category: "Document",
      description: "Read a PDF, DOCX, TXT, or MD file and produce a structured summary.",
      prompt: "Summarize the attached document structurally. Separate the core claims, important evidence, and follow-up questions.",
    },
    image_explain: {
      label: "Describe image",
      category: "Image",
      description: "Attach an image and ask the workspace to describe or compare what it sees.",
      prompt: "Describe the attached image. Split the visible elements, important context, and things I should verify.",
    },
    csv_analysis: {
      label: "Analyze table",
      category: "Data",
      description: "Inspect CSV, Excel, or pasted table columns, key numbers, and possible outliers.",
      prompt: "Profile this table deterministically and summarize the column structure, key figures, possible outliers, and next analysis steps.",
    },
    codex_task_prompt: {
      label: "Create Codex task prompt",
      category: "Code",
      description: "Turn situation, repo context, and acceptance criteria into a Codex-ready brief.",
      prompt: "Situation:\nWhat are you trying to change, and why?\n\nRelevant files:\n- \n\nConstraints:\n- Keep local-first behavior.\n\nAcceptance criteria:\n- \n\nTest commands:\n- python -m pytest",
    },
    investment_rebalancer: {
      label: "Investment rebalancer",
      category: "Investment",
      description: "Start a rebalancing workspace from CSV/YAML inputs.",
      prompt: "Use the portfolio CSV and target allocation YAML to summarize current weights, target gaps, and rebalance candidates.",
    },
    folder_index: {
      label: "Read folder structure",
      category: "Files",
      description: "Plan a file index for turning a local folder into an AIWS project.",
      prompt: "Propose file grouping and a workspace plan for turning this folder structure into an AIWS project.",
    },
  },
};

export const COPY_KO = {
  locale: "ko",
  productName: "AI Workbench Studio",
  shortName: "AIWS",
  tagline: "프로젝트, 파일, 추적 가능한 결과물을 연결하는 로컬 우선 AI 작업실.",
  brandCompact: "Workbench",
  nav: {
    home: "홈",
    newChat: "새 대화",
    newProject: "새 프로젝트",
    actions: "액션",
    projects: "프로젝트",
    chats: "대화",
    workspace: "작업실",
    oneOffChats: "일회성 대화",
    searchPlaceholder: "대화 제목 검색",
    noSearchResults: "검색 결과가 없습니다.",
  },
  topbar: {
    localFirst: "로컬 우선",
    contextOpen: "Context & Files 닫기",
    contextClosed: "Context & Files 열기",
    modeLabel: "모드",
  },
  home: {
    title: "로컬 AI 작업실",
    subtitle: "질문, 파일, 프로젝트에서 작업 세션을 시작하세요. 실행과 산출물은 추적 가능하게 남습니다.",
    workSessionEyebrow: "작업 시작",
    workSessionTitle: "작업 세션 시작",
    workSessionBody: "한 번 묻기, 파일에서 시작하기, 프로젝트 작업실 만들기 중에서 고르세요. 남길 가치가 있는 작업은 context, run, artifact로 기록됩니다.",
    laneAsk: "한 번 묻기",
    laneAskBody: "빠른 답변은 채팅으로 시작합니다.",
    laneFile: "파일에서 시작",
    laneFileBody: "PDF, 이미지, CSV, DOCX, 텍스트를 첨부합니다.",
    laneFileReady: "파일이 첨부됐습니다. 아래 액션을 고르세요.",
    laneProject: "프로젝트 만들기",
    laneProjectBody: "목표, 파일, 액션, 실행, 산출물을 함께 보관합니다.",
    factActions: "개 액션",
    factRuns: "개 저장된 실행",
    factArtifacts: "개 산출물",
    quickActions: "빠른 액션",
    quickActionsHint: "프로젝트 없이 먼저 결과물을 만들고, 쓸만한 흐름은 프로젝트로 저장합니다.",
    recentRuns: "최근 작업",
    recentArtifacts: "최근 산출물",
    artifacts: "산출물",
    configure: "설정",
    useInput: "첨부 파일 사용",
    prepareBrief: "내용 작성",
    createArtifact: "결과 만들기",
    createPrompt: "작업 지시 만들기",
    creating: "생성 중",
    notAvailable: "지원 예정",
    openTable: "표 열기",
    workbenchOutputs: "결과물",
    hintCreateTitle: "Workbench 결과물 만들기",
    hintCreateBody: "프로젝트를 만들기 전에도 문서, 이미지, CSV, 코드 작업을 시작할 수 있습니다.",
    hintInspectTitle: "작업과 산출물 확인",
    hintInspectBody: "각 결과물은 입력, 상태, 로그, 클릭 가능한 산출물을 함께 남깁니다.",
    hintPromoteTitle: "반복 작업으로 승격",
    hintPromoteBody: "쓸만한 흐름은 프로젝트, 액션, 설정 가능한 패널로 저장합니다.",
    attachRequired: "이 산출물을 만들려면 먼저 파일을 첨부하세요.",
    codexBriefRequired: "무엇을 위한 작업지시인지 상황과 목표를 먼저 적어주세요.",
    codexBriefHint: "먼저 상황, 관련 파일, 완료 기준을 적으면 Codex용 작업지시로 정리합니다.",
    runBeforeProject: "입력 하나로 결과 만들기",
    runHistory: "작업 기록",
    starterEmpty: "산출물이나 Codex 작업지시를 만들면 Plan, Log, 결과가 여기에 남습니다.",
    starterEmptyAction: "실제 Starter Action이 저장된 run을 만들기 전까지는 비어 있습니다.",
    artifactEmpty: "Markdown, CSV, JSON 같은 결과물이 클릭 가능한 객체로 표시됩니다.",
    artifactEmptyAction: "실행이 실제 파일을 쓴 뒤에 산출물이 나타납니다.",
  },
  table: {
    eyebrow: "표 작업대",
    title: "CSV, Excel, 붙여넣은 표 분석",
    emptyDrop: "CSV/XLS/XLSX를 끌어다 놓거나, 파일을 선택하거나, 아래에 표를 붙여넣으세요",
    pastedHint: "스프레드시트 셀을 복사해 붙여넣으면 임시 CSV 첨부로 바뀌고 표 미리보기가 채워집니다.",
    chooseFile: "파일 선택",
    analyze: "표 분석",
    analyzing: "분석 중...",
    close: "닫기",
    pastePlaceholder: "Excel, Numbers, Sheets의 셀이나 탭으로 구분된 표를 붙여넣으세요",
    noPreview: "아직 미리보기가 없습니다.",
    noPreviewHint: "CSV와 붙여넣은 표는 여기서 미리 볼 수 있습니다. XLS/XLSX는 실행할 때 백엔드에서 분석합니다.",
  },
  inspector: {
    title: "Context & Files",
    powerTitle: "Right Inspector",
    emptyPurpose: "대화를 시작하면 이 작업실이 참고하는 파일, 컨텍스트, 목표, 실행 기록, 진단 정보가 여기에 정리됩니다.",
    currentContext: "현재 컨텍스트",
    tabs: {
      context: "Context",
      files: "Files",
      memory: "Memory",
      runs: "Runs",
      artifacts: "Artifacts",
      diagnostics: "Diagnostics",
    },
    diagnosticsWarning: "공개 터널이 활성화되어 있습니다. 인증 없이 diagnostics를 노출하지 마세요.",
    factChunks: "chunks",
    factFiles: "files",
    factRuns: "runs",
    factArtifacts: "artifacts",
    includedChunks: "포함된 검색 chunk",
    currentTask: "현재 작업",
    local: "로컬",
    cloud: "클라우드",
    files: "파일",
    receipts: "영수증",
    calls: "호출",
    nextActions: "다음 작업",
    attachOrPaste: "입력 파일 추가 또는 표 붙여넣기",
    runAction: "표/문서 액션 실행",
    saveUsefulAnswer: "쓸만한 답변을 결과물로 저장",
    sendToCreateReceipt: "메시지를 보내 context receipt 만들기",
    promoteTitle: "프로젝트로 승격",
    promoteBody: "이 대화, 파일, receipt, 앞으로 만들 결과물을 새 private 프로젝트로 옮깁니다.",
    promote: "승격",
    promoting: "승격 중...",
    workSession: "WorkSession",
  },
  messageActions: {
    saveArtifact: "결과물로 저장",
    saving: "저장 중...",
  },
  settings: {
    title: "작업실 설정",
    close: "닫기",
    savedMessages: "저장 메시지",
    aiRequests: "AI 요청",
    monthlyApiCost: "이번 달 API 비용",
    profile: "프로필",
    avatar: "프로필 사진",
    name: "이름",
    age: "나이",
    role: "직업 / 역할",
    language: "언어",
    personalContext: "개인 컨텍스트",
    situation: "상황 / 대화 컨텍스트",
    addMemory: "기억에 추가",
    memoryPlaceholder: "Workbench가 앞으로 기억하면 좋은 내용을 적어주세요.",
    interface: "인터페이스",
    uiMode: "사용 모드",
    easyMode: "Easy Mode - 쉬운 화면",
    powerMode: "Power Mode - 운영자 화면",
    modeHelp: "Easy는 모델 선택과 파일 첨부는 그대로 두고 운영자 로그를 숨깁니다. Power는 실행 경로, 비용, prompt, runtime을 확인하는 화면입니다.",
    saveProfile: "프로필 저장",
  },
  modelPicker: {
    title: "AI 모델 선택",
    selected: "사용 중",
    groups: {
      recommended: "추천",
      local: "로컬",
      fast: "빠른 작업",
      long: "긴 문서",
      reasoning: "추론",
      coding: "코딩",
      all: "전체",
    },
  },
  search: {
    off: "검색 끔",
    auto: "로컬 컨텍스트 우선",
    always: "웹 검색",
  },
  chat: {
    emptyTitle: "무엇을 도와드릴까요?",
    emptyBody: "이 작업실은 준비되었습니다. 모델을 고르거나, 파일을 첨부하거나, Context & Files를 열어보세요.",
    assistantThinking: "Workbench가 생각 중",
    preparing: "Workbench가 답변을 준비 중",
    attachFile: "파일 추가",
    placeholder: "무엇이든 물어보세요",
    quickPrompts: ["이미지 설명하기", "문서 요약하기", "할 일 정리하기", "글쓰기 도와줘"],
  },
  starterActions: {
    document_summary: {
      label: "문서 요약하기",
      category: "문서",
      description: "PDF, DOCX, TXT, MD 파일을 읽고 구조화된 요약을 만듭니다.",
      prompt: "첨부한 문서를 구조적으로 요약해줘. 핵심 주장, 중요한 근거, 후속 질문을 나눠서 정리해줘.",
    },
    image_explain: {
      label: "이미지 설명하기",
      category: "이미지",
      description: "이미지를 첨부하면 보이는 내용과 확인할 점을 정리합니다.",
      prompt: "첨부한 이미지를 설명해줘. 보이는 요소, 중요한 맥락, 사람이 확인해야 할 점을 나눠서 정리해줘.",
    },
    csv_analysis: {
      label: "표 분석하기",
      category: "데이터",
      description: "CSV, Excel, 붙여넣은 표의 컬럼, 주요 숫자, 결측치와 다음 분석 방향을 확인합니다.",
      prompt: "이 표를 deterministic profile로 분석하고 컬럼 구조, 주요 수치, 결측치, 이상치 가능성, 다음 분석 단계를 정리해줘.",
    },
    codex_task_prompt: {
      label: "Codex 작업지시 만들기",
      category: "코드",
      description: "상황, 저장소 맥락, 완료 기준을 Codex가 바로 실행할 수 있는 작업지시로 정리합니다.",
      prompt: "상황:\n무엇을 바꾸려는지, 왜 필요한지 적어주세요.\n\n관련 파일:\n- \n\n제약:\n- local-first 동작은 유지합니다.\n\n완료 기준:\n- \n\n테스트 명령:\n- python -m pytest",
    },
    investment_rebalancer: {
      label: "투자 리밸런싱",
      category: "투자",
      description: "CSV/YAML 입력으로 리밸런싱 작업실을 시작합니다.",
      prompt: "포트폴리오 CSV와 목표 배분 YAML을 바탕으로 현재 비중, 목표 차이, 리밸런싱 후보를 정리해줘.",
    },
    folder_index: {
      label: "폴더 구조 읽기",
      category: "파일",
      description: "로컬 폴더를 AIWS 프로젝트로 바꾸기 위한 파일 인덱스를 계획합니다.",
      prompt: "이 폴더 구조를 AIWS 프로젝트로 만들기 위한 파일 그룹과 작업실 계획을 제안해줘.",
    },
  },
};

function mergeCopy(base, override) {
  const output = { ...base };
  Object.entries(override || {}).forEach(([key, value]) => {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      output[key] = mergeCopy(base[key] || {}, value);
    } else {
      output[key] = value;
    }
  });
  return output;
}

export function copyForLocale(locale = "en") {
  return String(locale || "").toLowerCase().startsWith("ko")
    ? mergeCopy(COPY_EN, COPY_KO)
    : COPY_EN;
}

export function copyForAccount(account) {
  return copyForLocale(account?.profile?.language || "en");
}

export const COPY = COPY_EN;
